//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserMenu = new HashSet<UserMenu>();
        }
    
        public int UserId { get; set; }
        public string NameUser { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> LifeStyleId { get; set; }
        public Nullable<int> BMR { get; set; }
        public Nullable<int> PassStoreId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual LifeStyle LifeStyle { get; set; }
        public virtual PassStore PassStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenu> UserMenu { get; set; }
    }
}
